### ISSUE TITLE
Defaulting to localgov_scarfolk when enabling localgov_demo content.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_scarfolk#1]
Hi @markconroy ! 

I'm super keen to make this the default theme when we enable localgov_demo module, to show off the distribution in the best possible light. 

What do we need to do to make this happen?

Cheers,

Finn

**Comment by finnlewis** [comment]
Here's a screenshot of the home page as is with the latest localgov_demo content: 

![image](https://user-images.githubusercontent.com/326588/134490634-e5748705-ccc2-4d7d-98bb-d47f5c32fbe0.png)

**Comment by markconroy** [comment]
Is this still an issue? I _think_ Scarfolk is enabled as default, by default.

**Comment by finnlewis** [comment]
Agreed! I guess many things have moved on since September 2021 :)

Thanks @markconroy
