### ISSUE TITLE
Create release - 1.0

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_scarfolk#2]
I think this is ready for a 1.0 release. Any objections? 

It would be great to have a 1.0 before DrupalCon and to have this theme enabled on our demo.localgovdrupal.org site.

**Comment by finnlewis** [comment]
Yes yes yes! Want a quick chat about it?

**Comment by finnlewis** [comment]
I've gone ahead and created a release @markconroy 

Might we want to expand on the release notes?

https://github.com/localgovdrupal/localgov_scarfolk/releases/tag/1.0.0

**Comment by markconroy** [comment]
Looks good to me.
