### ISSUE TITLE
Drupal 10 support 

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_scarfolk#22]
Issue to track any changes needed to support Drupal 10

**Comment by finnlewis** [comment]
@stephen-cox suggests we test this : 

- Install it in a Drupal 9 site and run the update status module.
- Install on a Drupal 10 site
- Confirm any tests are running.
- Check any JavaScript (manually)

**Comment by markconroy** [comment]
This theme is just a html.html.twig file and some CSS. There's really nothing else to it. I don't see how it could break in D10 as long as #25 is merged.
