### ISSUE TITLE
Insufficient contrast between --color-accent and grey background

### ISSUE THREAD

**Issue by bisd** [localgovdrupal/localgov_scarfolk#31]
The blue text in grey boxes does not contain enough contrast (3.49) between background and foreground colour.

I have added a screenshot for an example of said box on the Subsite example page for different page components.

https://test.localgovdrupal.org/test-subsite-demo-all-components/example-page-different-page-com

@msayoung 

![hcm_scarfolk1](https://github.com/localgovdrupal/localgov_scarfolk/assets/2633608/a4cc2f2f-0f89-4867-953c-c45d3752b055)

**Comment by markconroy** [comment]
Looks like this is a localgov_base issue, not just Scarfolk. This should fix it: https://github.com/localgovdrupal/localgov_base/pull/493
